### ISSUE TITLE
Novacom installation

### ISSUE THREAD

**Issue by paulnwale** [123Haynes/universal-novacom-installer#1]
I downloaded the latest release of universal installer. I have java installed on my win 7 32 bit, but double clicking the installer nothing happens. please help
im trying to install TPToolbox to do a clean install. 

Thanks

**Comment by 123Haynes** [comment]
Hi,

try to execute it from the command line with:

``` bash
java -jar UniversalNovacomInstaller-1.4.1.jar
```

That should give you at least an errormessage so we can narrow down where it fails.

**Comment by 123Haynes** [comment]
@paulnwale I haven't heard from you in 2 month so I assume that you found a solution.
If you stil need help feel free to reopen this issue.
